services:
  product-service:
    build:
      context: .
      dockerfile: apps/product-service/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - microservices-network

  order-service:
    build:
      context: .
      dockerfile: apps/order-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:3001
    depends_on:
      - product-service
    networks:
      - microservices-network

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    environment: 
      - PRODUCT_SERVICE_URL=http://product-service:3001
      - ORDER_SERVICE_URL=http://order-service:3002
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
